# Generated by Django 2.2 on 2022-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
